#!/usr/bin/env python3
#!/usr/bin/env python3

class Rectangle:
    def __init__(self, height=0.0, width=0.0):
        self.height = height
        self.width = width


    def get_perimeter(self):
        sum = int(self.height + self.height + self.width + self.width)
        return sum

    def get_area(self):
        return self.height * self.width

    def draw(self):
        for i in range(self.height):
            if i in [0]:
                print("* " * (self.width))
            elif i in [(self.height - 1)]:
                print("* " * (self.width))
            else:
                print("*" + "  " * (self.width - 2) + " *")






class Square(Rectangle):
    def __init__(self, height=0.0, width=0.0, length=0.0):
        # call the contrcutor of the superclass
        Rectangle.__init__(self, height=0.0, width=0.0)

        self.length = length

    # override the Rectangle method
    def get_perimeter(self):
        perimeter = (self.length + self.length + self.length + self.length)
        return perimeter




    def get_area(self):
        return self.length * self.length


    def draw(self):
        for i in range(self.length):
            if i in [0]:
                print("* " * (self.length))
            elif i in [(self.length - 1)]:
                print("* " * (self.length))
            else:
                print("*" + "  " * (self.length - 2) + " *")








def shape_calr(shape1):

        print("Perimeter:  ", shape1.get_perimeter())
        print("Area:       " ,shape1.get_area())
        shape1.draw()
        return


def shape_cals(shape2):

        print("Perimeter: ", shape2.get_perimeter())
        print("Area:      ", shape2.get_area())
        shape2.draw()

        return

def main():
    print("Rectangle Calculator")
    print()

    while True:
        shape = input("Rectangle or Square? (r/s):  ")
        if shape == "r":
            height = int(input("Height:      "))
            width = int(input("Width:       "))

            shape1 = Rectangle(height, width)
            shape_calr(shape1)
            print()
        elif shape == "s":
            length = int(input("Length:     "))
            shape2 = Square(0, 0, length)
            shape_cals(shape2)
            print()


        choice = input("Continue? (y/n): ")
        print()
        if choice != "y":
            print("Bye!")
            break


if __name__ == "__main__":
    main()
